#!/usr/bin/env ruby

type = ARGV[0]
type ||= 'dev'

supported_types = %w{dev test}
if !supported_types.member?(type) or Dir.glob('gamesoup').empty?
  puts "Usage:\n\tscript/dumpdata [#{supported_types.join '|'}]"
  exit
end

Dir.chdir('gamesoup')
%w{library games matches}.each do |app|
  dumpdest = "#{app}/fixtures/#{type}-#{app}.json"
  if File.exists? dumpdest
    puts "Backing up #{dumpdest}"
    `cp #{dumpdest} #{app}/fixtures/#{type}-#{app}_#{Time.now.strftime '%Y-%m-%d_%H:%M:%S'}_backup.json`
  end
  puts "Dumping to #{dumpdest}"
  `./manage.py dumpdata --indent=4 #{app} > #{dumpdest}`
end
