#!/usr/bin/env ruby

type = ARGV[0]
type ||= 'dev'

supported_types = %w{dev test}
if !supported_types.member?(type) or Dir.glob('gamesoup').empty?
  puts "Usage:\n\tscript/loaddata [#{supported_types.join '|'}]"
  exit
end

Dir.chdir('gamesoup')
puts "Loading #{type} user data"
`./manage.py loaddata ../fixtures/#{type}-data.json`
%w{library games matches}.each do |app|
  original = "#{app}/fixtures/#{type}-#{app}.json"
  if File.size(original) > 3
    puts "Loading #{type} #{app} data"
    `./manage.py loaddata #{original}`
  end
end
