#!/usr/bin/env bash
rm db/development.sqlite
gamesoup/manage.py syncdb
gamesoup/manage.py loaddata fixtures/test-data.json
gamesoup/manage.py loaddata gamesoup/library/fixtures/test-library.json
gamesoup/manage.py loaddata gamesoup/games/fixtures/test-games.json
